// @flow
const SET_FILTERING = 'SET_FILTERING';
const SET_SORTING = 'SET_SORTING';
const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';

const GET_MOVIES = 'GET_MOVIES';
const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
const GET_MOVIES_FAIL = 'GET_MOVIES_SUCCESS_FAIL';

const GET_GENRES = 'GET_GENRES';
const GET_GENRES_SUCCESS = 'GET_GENRES_SUCCESS';
const GET_GENRES_FAIL = 'GET_GENRES_FAIL';

const SEARCH_MOVIES = 'SEARCH_MOVIES';
const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';
const SEARCH_MOVIES_FAIL = 'SEARCH_MOVIES_FAIL';

const GET_DETAILS = 'GET_DETAILS';
const GET_DETAILS_SUCCESS = 'GET_DETAILS_SUCCESS';
const GET_DETAILS_FAIL = 'GET_DETAILS_FAIL';

const GET_CASTS = 'GET_CASTS';
const GET_CASTS_SUCCESS = 'GET_CASTS_SUCCESS';
const GET_CASTS_FAIL = 'GET_CASTS_FAIL';

const GET_IMAGES = 'GET_IMAGES';
const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS';
const GET_IMAGES_FAIL = 'GET_IMAGES_FAIL';

export {
  SET_SORTING, SET_FILTERING, SET_SEARCH_QUERY,
  GET_MOVIES, GET_MOVIES_SUCCESS, GET_MOVIES_FAIL,
  GET_GENRES, GET_GENRES_SUCCESS, GET_GENRES_FAIL,
  SEARCH_MOVIES, SEARCH_MOVIES_SUCCESS, SEARCH_MOVIES_FAIL,
  GET_DETAILS, GET_DETAILS_SUCCESS, GET_DETAILS_FAIL,
  GET_CASTS, GET_CASTS_SUCCESS, GET_CASTS_FAIL,
  GET_IMAGES, GET_IMAGES_SUCCESS, GET_IMAGES_FAIL,
};
